=== npikayy/XML/buoi4_NguyenPhucKhang/bài 2/dssv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="maType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="10"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tenType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sdtType">
        <xs:restriction base="xs:string">
            <xs:pattern value="0\d{9}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tenkhoaType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[\p{L}\s]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="KHOA">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MAKHOA" type="maType"/>
                <xs:element name="TENKHOA" type="tenkhoaType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="LOP">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MALOP" type="maType"/>
                <xs:element name="TENLOP" type="tenType"/>
                <xs:element name="MAKHOA" type="maType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="SINHVIEN">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="MASV" type="maType"/>
                <xs:element name="HOTEN" type="tenType"/>
                <xs:element name="NGAYSINH" type="xs:date"/>
                <xs:element name="DIACHI" type="xs:string"/>
                <xs:element name="SDT" type="sdtType"/>
                <xs:element name="MALOP" type="maType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="DSSV">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="KHOA" maxOccurs="unbounded"/>
                <xs:element ref="LOP" maxOccurs="unbounded"/>
                <xs:element ref="SINHVIEN" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="PK_KHOA">
            <xs:selector xpath="KHOA"/>
            <xs:field xpath="MAKHOA"/>
        </xs:key>

        <xs:key name="PK_LOP">
            <xs:selector xpath="LOP"/>
            <xs:field xpath="MALOP"/>
        </xs:key>

        <xs:key name="PK_SINHVIEN">
            <xs:selector xpath="SINHVIEN"/>
            <xs:field xpath="MASV"/>
        </xs:key>

        <xs:keyref name="FK_LOP_KHOA" refer="PK_KHOA">
            <xs:selector xpath="LOP"/>
            <xs:field xpath="MAKHOA"/>
        </xs:keyref>

        <xs:keyref name="FK_SINHVIEN_LOP" refer="PK_LOP">
            <xs:selector xpath="SINHVIEN"/>
            <xs:field xpath="MALOP"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== npikayy/XML/buoi4_NguyenPhucKhang/bài 2/dssv.xml
<?xml version="1.0" encoding="UTF-8"?>
<DSSV xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:noNamespaceSchemaLocation="DSSV.xsd">
    <KHOA>
        <MAKHOA>CNTT</MAKHOA>
        <TENKHOA>Công Nghệ Thông Tin</TENKHOA>
    </KHOA>
    <KHOA>
        <MAKHOA>KT</MAKHOA>
        <TENKHOA>Kế Toán</TENKHOA>
    </KHOA>

     <LOP>
        <MALOP>CNTTK10</MALOP>
        <TENLOP>Cong nghe thong tin 2022</TENLOP>
        <MAKHOA>CNTT</MAKHOA>
    </LOP>
     <LOP>
        <MALOP>KTK10</MALOP>
        <TENLOP>Kế Toán 2022</TENLOP>
        <MAKHOA>KT</MAKHOA>
    </LOP>

    <SINHVIEN>
        <MASV>SV001</MASV>
        <HOTEN>Huỳnh Đăng Khoa</HOTEN>
        <NGAYSINH>2004-01-01</NGAYSINH>
        <DIACHI>Cần Thơ</DIACHI>
        <SDT>0123456789</SDT>
        <MALOP>CNTTK10</MALOP>
    </SINHVIEN>

    <SINHVIEN>
        <MASV>SV002</MASV>
        <HOTEN>Lê Văn Mộng</HOTEN>
        <NGAYSINH>2004-01-01</NGAYSINH>
        <DIACHI>Cần Thơ</DIACHI>
        <SDT>0123456789</SDT>
        <MALOP>CNTTK10</MALOP>
    </SINHVIEN>

     <SINHVIEN>
        <MASV>SV003</MASV>
        <HOTEN>Le Van Dinh</HOTEN>
        <NGAYSINH>2004-07-10</NGAYSINH>
        <DIACHI>Da Nang</DIACHI>
        <SDT>0912345678</SDT>
        <MALOP>KTK10</MALOP>
    </SINHVIEN>
</DSSV>
